name: Add Labels to PR Author

on:
  pull_request:
    types:
      - opened

jobs:
  add-label:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR is from the same user
        id: check-user
        run: |
          if [[ "${{ github.event.pull_request.user.login }}" == "${{ github.actor }}" ]]; then
            echo "::set-output name=is_same_user::true"
          else
            echo "::set-output name=is_same_user::false"
          fi

      - name: Add Labels to PR Author
        if: steps.check-user.outputs.is_same_user == 'true'
        uses: actions/labeler@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          labels: 'hacktoberfest, hacktoberfest-accepted'
